# Generated by Django 2.1.5 on 2019-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10000)),
                ('info', models.CharField(max_length=100000000)),
                ('author', models.CharField(max_length=10000)),
                ('catalog', models.CharField(max_length=10000)),
                ('photo', models.CharField(max_length=10000)),
                ('card', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('art_path', models.CharField(max_length=100000000)),
                ('number', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('money', models.CharField(max_length=30)),
                ('card', models.CharField(max_length=30)),
            ],
        ),
    ]
