# Generated by Django 2.1.5 on 2019-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app64', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='book_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='card',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='catalog',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='art_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
