# Generated by Django 2.1.5 on 2019-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app64', '0006_auto_20190605_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
    ]
