# Generated by Django 2.1.5 on 2019-06-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app64', '0007_auto_20190605_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Photo',
        ),
    ]
