# Generated by Django 2.1.5 on 2019-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app64', '0008_auto_20190605_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='personintroduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonName', models.CharField(max_length=30)),
                ('PersonLabel', models.CharField(max_length=30)),
                ('PersonImg', models.CharField(max_length=30)),
                ('PersonArticle', models.CharField(max_length=1000)),
                ('PersonTime', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=20)),
                ('ImgName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
