# Generated by Django 2.1.5 on 2019-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app64', '0009_auto_20190605_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30)),
                ('B_Info', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=30)),
                ('Catalog', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=20)),
                ('Card', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(max_length=30)),
                ('Art_path', models.CharField(max_length=80)),
                ('Number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Use_name', models.CharField(max_length=20)),
                ('Book_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Level', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Money', models.CharField(max_length=30)),
                ('Card', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='personintroduce',
        ),
        migrations.DeleteModel(
            name='usertable',
        ),
    ]
